baseURL = 'https://laboratorij-km.github.io/ime-priimek/' # change member_repository to your repository name
# languageCode = 'en-us'
title = 'Member Hugo Template'
theme = "member-theme"

[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
    [languages.en.params]
      flag = "flag-icon-us"
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "About"
        url = "/" 
        weight = 100
      [[languages.en.menus.main]]
        name = "Lecturing"
        url = "/lecturing/" 
        weight = 200
      [[languages.en.menus.main]]
        name = "Projects"
        url = "/projects/" 
        weight = 300

  [languages.si]
    contentDir = 'content/slovene'
    languageName = 'Slovene'
    weight = 10
    [languages.si.params]
      flag = "flag-icon-si"
    [languages.si.menus]
      [[languages.si.menus.main]]
        name = "O meni"
        url = "/si/" 
        weight = 100
      [[languages.si.menus.main]]
        name = "Poučevanje"
        url = "/si/lecturing/" 
        weight = 200
      [[languages.si.menus.main]]
        name = "Projekti"
        url = "/si/projects/" 
        weight = 300

[markup.goldmark.renderer] 
  unsafe= true

